sudo: required

language: python

services:
  - docker

env:
  global:
    - ON_TRAVIS=True
    - SECRET_KEY='tT\xd7\xb06\xf7\x9b\xff\x0fZL\xca\xca\x11\xefM\xacr\xfb\xdf\xca\x9b'
    - DJANGO_SETTINGS_MODULE=core.settings.travis_docker
    - ALL_FILE=all.travis.yml
    - COMPOSE_PROJECT_NAME=bims
    - COMPOSE_FILE=deployment/docker-compose.travis.yml:deployment/docker-compose.override.yml
    - MONITORING_ENABLED=False

matrix:
  include:
    - python: 2.7
      env: PYTHON=2.7

addons:
  hosts:
    - uwsgi

before_install:
  # install ansible
  - sudo apt-get -y update
  - sudo apt-get -y install libssl-dev
  - sudo pip install ansible

install:
  - pip install coveralls
  - pip install -r REQUIREMENTS-dev.txt
  - pip install -U docker-compose
  # setup files
  - cp deployment/ansible/development/group_vars/${ALL_FILE} deployment/ansible/development/group_vars/all.yml
  - make setup-ansible ANSIBLE_ARGS="--extra-vars='pycharm_version=\"\"' --skip-tags=development"
  # show docker-compose.override.yml for debugging
  - cat deployment/docker-compose.override.yml
  - make build
  - make up-travis
  # Wait until database migrations ready
  - until make sync; do echo "Retrying"; sleep 5; done
  # Show container status
  - source compose.env.sh
  - docker-compose ps

script:
  - make flake8-check
  - make coverage-django-test ARGS="--log-level ERROR" CMD_ARGS="--verbosity 3"

after_success:
  - coverage combine
  # Replace parent directory to travis directory, because we are running
  # coverage using docker mount
  - sed -i 's/home\/web\/django_project/home\/travis\/build\/inasafe\/inasafe-django\/django_project/g' .coverage
  - cat .coverage
  - coveralls

email:
 - dimas@kartoza.com
