---
# Set to yes, if you're using pycharm for development
# Otherwise, set no
use_pycharm: yes
# Your linux/mac user that will run ansible
remote_user: lucernae
# Your linux/mac group that will run ansible
remote_group: staff
# Your project location (this repo)
project_path: "/Users/lucernae/Documents/WorkingDir/Projects/kartoza/django-bims"
# True if it will be running on Travis
on_travis: False

django:
  environment:
    SITE_DOMAIN_NAME: 'http://django-bims.test'
    GEOCONTEXT_URL: 'https://geocontext.kartoza.com'
    GEOCONTEXT_COLLECTION_KEY: 'climate'
    CONTACT_US_EMAIL: 'dimas@kartoza.com'
    DEBUG: True
    DJANGO_SETTINGS_MODULE: core.settings.dev_docker
    RABBITMQ_HOST: rabbitmq
    PYTHONPATH: /usr/src/app:/home/web/django_project
    ROOT_URLCONF: core.urls
    DATABASE_NAME: gis
    DATABASE_PASSWORD: docker
    DATABASE_USERNAME: docker
    DATABASE_HOST: db
    SITEURL: http://django-bims.test/
    GEOSERVER_LOCATION_SITE_LAYER: bims:location_site_view

geonode:
  environment:
    GEONODE_INSTANCE_NAME: geonode
    DEFAULT_BACKEND_DATASTORE: datastore
    GEONODE_DATABASE: gis
    GEONODE_DATABASE_USER: docker
    GEONODE_DATABASE_PASSWORD: docker
    GEONODE_GEODATABASE: geonode_data
    GEONODE_GEODATABASE_PASSWORD: geonode_data
    UWSGI_CMD: uwsgi --ini /usr/src/app/uwsgi.ini
    IS_CELERY: False
    C_FORCE_ROOT: 1
    # replaced with defaults in settings
    # Must have protocol
    GEOSERVER_PUBLIC_LOCATION: http://django-bims.test/geoserver/
    GEOSERVER_LOCATION: http://geoserver:8080/geoserver/
    STATIC_ROOT: /home/web/static/static
    MEDIA_ROOT: /home/web/media
    GEOIP_PATH: /home/web/media/geoip.db
    ALLOWED_HOSTS: ['django-bims.test']
    ADMIN_EMAILS: dimas@kartoza.com
    GEOSERVER_ADMIN_PASSWORD: admingeoserver
    ASYNC_SIGNALS_GEONODE: True

geoserver:
  environment:
    GEOSERVER_ADMIN_PASSWORD: admingeoserver
    SITEURL: http://django-bims.test/

interpreters:
  inasafe_django:
    name: 'Django-BIMS Container'
    domain_alias: 'django-bims.test'
    ssh_port: &inasafe_django_ssh_port 63303
    pycharm_helpers: /home/web/django_project/.pycharm_helpers
    ipaddress: &inasafe_django_host_ip django-bims.test

docker_port_forward:
  django:
    db: 6543
    http: 63302
    ssh: 63303
    karma_tests: 63304
    geoserver: 63305
    gbif_ipt: 63308