---

# Set to yes, if you're using pycharm for development
# Otherwise, set no
use_pycharm: no
# Your linux/mac user that will run ansible
remote_user: travis
# Your linux/mac group that will run ansible
remote_group: travis
# Your project location (this repo)
project_path: "/home/travis/build/kartoza/django-bims"
# True if it will be running on Travis
on_travis: True

django:
  environment:
    SITE_DOMAIN_NAME: 'http://uwsgi'
    GEOCONTEXT_URL: 'http://localhost:65402'
    GEOCONTEXT_COLLECTION_KEY: 'climate'
    CONTACT_US_EMAIL: 'dimas@kartoza.com'
    DEBUG: True
    DJANGO_SETTINGS_MODULE: core.settings.dev_docker
    RABBITMQ_HOST: rabbitmq
    HAYSTACK_HOST: elasticsearch
    PYTHONPATH: /usr/src/app:/home/web/django_project
    ROOT_URLCONF: core.urls
    DATABASE_NAME: gis
    DATABASE_PASSWORD: docker
    DATABASE_USERNAME: docker
    DATABASE_HOST: db
    SITEURL: http://uwsgi/
    SECRET_KEY: 'tT\xd7\xb06\xf7\x9b\xff\x0fZL\xca\xca\x11\xefM\xacr\xfb\xdf\xca\x9b'

geonode:
  environment:
    GEONODE_INSTANCE_NAME: geonode
    DEFAULT_BACKEND_DATASTORE: datastore
    GEONODE_DATABASE: gis
    GEONODE_DATABASE_USER: docker
    GEONODE_DATABASE_PASSWORD: docker
    GEONODE_GEODATABASE: geonode_data
    GEONODE_GEODATABASE_PASSWORD: geonode_data
    UWSGI_CMD: uwsgi --ini /usr/src/app/uwsgi.ini
    IS_CELERY: False
    C_FORCE_ROOT: 1
    # replaced with defaults in settings
    GEOSERVER_PUBLIC_LOCATION: http://uwsgi/geoserver/
    GEOSERVER_LOCATION: http://geoserver:8080/geoserver/
    STATIC_ROOT: /home/web/static
    MEDIA_ROOT: /home/web/media
    GEOIP_PATH: /home/web/media/geoip.db
    ALLOWED_HOSTS: ['uwsgi']
    ADMIN_EMAILS: dimas@kartoza.com
    GEOSERVER_ADMIN_PASSWORD: admingeoserver

geoserver:
  environment:
    GEOSERVER_ADMIN_PASSWORD: admingeoserver
    SITEURL: http://uwsgi/

interpreters:
  inasafe_django:
    name: 'Django-BIMS Container'
    domain_alias: 'uwsgi'
    ssh_port: &inasafe_django_ssh_port 63303
    pycharm_helpers: /home/web/django_project/.pycharm_helpers
    ipaddress: &inasafe_django_host_ip uwsgi

docker_port_forward:
  django:
    db: 6543
    elastic_search: 9200
    http: 80
    ssh: 63303
    karma_tests: 63304
